// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"database/sql"
	"time"
)

type ChildCounter struct {
	ParentID  string `json:"parent_id"`
	LastChild int32  `json:"last_child"`
}

type Comment struct {
	ID        string    `json:"id"`
	IssueID   string    `json:"issue_id"`
	Author    string    `json:"author"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

type Dependency struct {
	IssueID     string    `json:"issue_id"`
	DependsOnID string    `json:"depends_on_id"`
	Type        string    `json:"type"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   string    `json:"created_by"`
	Metadata    string    `json:"metadata"`
	ThreadID    string    `json:"thread_id"`
}

type Event struct {
	ID        string    `json:"id"`
	IssueID   string    `json:"issue_id"`
	EventType string    `json:"event_type"`
	Actor     string    `json:"actor"`
	OldValue  string    `json:"old_value"`
	NewValue  string    `json:"new_value"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

type Issue struct {
	ID                 string       `json:"id"`
	ContentHash        string       `json:"content_hash"`
	Title              string       `json:"title"`
	Description        string       `json:"description"`
	Design             string       `json:"design"`
	AcceptanceCriteria string       `json:"acceptance_criteria"`
	Notes              string       `json:"notes"`
	Status             string       `json:"status"`
	Priority           int32        `json:"priority"`
	IssueType          string       `json:"issue_type"`
	Assignee           string       `json:"assignee"`
	EstimatedMinutes   int32        `json:"estimated_minutes"`
	CreatedAt          time.Time    `json:"created_at"`
	CreatedBy          string       `json:"created_by"`
	Owner              string       `json:"owner"`
	UpdatedAt          time.Time    `json:"updated_at"`
	ClosedAt           sql.NullTime `json:"closed_at"`
	ClosedBySession    string       `json:"closed_by_session"`
	ExternalRef        string       `json:"external_ref"`
	SpecID             string       `json:"spec_id"`
	Metadata           string       `json:"metadata"`
	SourceRepo         string       `json:"source_repo"`
	SourceSystem       string       `json:"source_system"`
	CloseReason        string       `json:"close_reason"`
	Sender             string       `json:"sender"`
	Ephemeral          int32        `json:"ephemeral"`
	Pinned             int32        `json:"pinned"`
	IsTemplate         int32        `json:"is_template"`
	WispType           string       `json:"wisp_type"`
	MolType            string       `json:"mol_type"`
	RoleType           string       `json:"role_type"`
	EventKind          string       `json:"event_kind"`
	Actor              string       `json:"actor"`
	Target             string       `json:"target"`
	Payload            string       `json:"payload"`
	StartedAt          sql.NullTime `json:"started_at"`
	DueAt              sql.NullTime `json:"due_at"`
	DeferUntil         sql.NullTime `json:"defer_until"`
}

type Label struct {
	IssueID string `json:"issue_id"`
	Label   string `json:"label"`
}
