// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pgdb

import (
	"context"
	"database/sql"
	"time"
)

const addComment = `-- name: AddComment :exec
INSERT INTO comments (id, issue_id, author, text, created_at)
VALUES ($1, $2, $3,
        $4, $5)
`

type AddCommentParams struct {
	ID        string    `json:"id"`
	IssueID   string    `json:"issue_id"`
	Author    string    `json:"author"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) error {
	_, err := q.db.ExecContext(ctx, addComment,
		arg.ID,
		arg.IssueID,
		arg.Author,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const addDependency = `-- name: AddDependency :exec
INSERT INTO dependencies (issue_id, depends_on_id, type, created_at, created_by, metadata, thread_id)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7
)
`

type AddDependencyParams struct {
	IssueID     string    `json:"issue_id"`
	DependsOnID string    `json:"depends_on_id"`
	Type        string    `json:"type"`
	CreatedAt   time.Time `json:"created_at"`
	CreatedBy   string    `json:"created_by"`
	Metadata    string    `json:"metadata"`
	ThreadID    string    `json:"thread_id"`
}

func (q *Queries) AddDependency(ctx context.Context, arg AddDependencyParams) error {
	_, err := q.db.ExecContext(ctx, addDependency,
		arg.IssueID,
		arg.DependsOnID,
		arg.Type,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Metadata,
		arg.ThreadID,
	)
	return err
}

const addLabel = `-- name: AddLabel :exec
INSERT INTO labels (issue_id, label) VALUES ($1, $2)
`

type AddLabelParams struct {
	IssueID string `json:"issue_id"`
	Label   string `json:"label"`
}

func (q *Queries) AddLabel(ctx context.Context, arg AddLabelParams) error {
	_, err := q.db.ExecContext(ctx, addLabel, arg.IssueID, arg.Label)
	return err
}

const blocksReachableFrom = `-- name: BlocksReachableFrom :many
SELECT depends_on_id FROM dependencies
WHERE issue_id = $1 AND type = $2
`

type BlocksReachableFromParams struct {
	IssueID string `json:"issue_id"`
	Type    string `json:"type"`
}

func (q *Queries) BlocksReachableFrom(ctx context.Context, arg BlocksReachableFromParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, blocksReachableFrom, arg.IssueID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var depends_on_id string
		if err := rows.Scan(&depends_on_id); err != nil {
			return nil, err
		}
		items = append(items, depends_on_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countIssuesWithPrefix = `-- name: CountIssuesWithPrefix :one
SELECT COUNT(*) FROM issues
WHERE id LIKE $1
`

// Used by the adaptive id-length selector: more issues -> longer hash.
func (q *Queries) CountIssuesWithPrefix(ctx context.Context, likePattern string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesWithPrefix, likePattern)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :exec

INSERT INTO issues (
    id, content_hash, title, description, design, acceptance_criteria, notes,
    status, priority, issue_type, assignee, estimated_minutes,
    created_at, created_by, owner, updated_at, started_at, closed_at, closed_by_session,
    external_ref, spec_id, metadata, source_repo, source_system, close_reason,
    sender, ephemeral, pinned, is_template,
    wisp_type, mol_type, role_type,
    event_kind, actor, target, payload,
    due_at, defer_until
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7,
    $8, $9, $10,
    $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19,
    $20, $21, $22,
    $23, $24, $25,
    $26, $27, $28,
    $29,
    $30, $31, $32,
    $33, $34, $35,
    $36,
    $37, $38
)
`

type CreateIssueParams struct {
	ID                 string       `json:"id"`
	ContentHash        string       `json:"content_hash"`
	Title              string       `json:"title"`
	Description        string       `json:"description"`
	Design             string       `json:"design"`
	AcceptanceCriteria string       `json:"acceptance_criteria"`
	Notes              string       `json:"notes"`
	Status             string       `json:"status"`
	Priority           int32        `json:"priority"`
	IssueType          string       `json:"issue_type"`
	Assignee           string       `json:"assignee"`
	EstimatedMinutes   int32        `json:"estimated_minutes"`
	CreatedAt          time.Time    `json:"created_at"`
	CreatedBy          string       `json:"created_by"`
	Owner              string       `json:"owner"`
	UpdatedAt          time.Time    `json:"updated_at"`
	StartedAt          sql.NullTime `json:"started_at"`
	ClosedAt           sql.NullTime `json:"closed_at"`
	ClosedBySession    string       `json:"closed_by_session"`
	ExternalRef        string       `json:"external_ref"`
	SpecID             string       `json:"spec_id"`
	Metadata           string       `json:"metadata"`
	SourceRepo         string       `json:"source_repo"`
	SourceSystem       string       `json:"source_system"`
	CloseReason        string       `json:"close_reason"`
	Sender             string       `json:"sender"`
	Ephemeral          int32        `json:"ephemeral"`
	Pinned             int32        `json:"pinned"`
	IsTemplate         int32        `json:"is_template"`
	WispType           string       `json:"wisp_type"`
	MolType            string       `json:"mol_type"`
	RoleType           string       `json:"role_type"`
	EventKind          string       `json:"event_kind"`
	Actor              string       `json:"actor"`
	Target             string       `json:"target"`
	Payload            string       `json:"payload"`
	DueAt              sql.NullTime `json:"due_at"`
	DeferUntil         sql.NullTime `json:"defer_until"`
}

// Dialect-portable queries: named args via sqlc.arg() so both `?` (sqlite)
// and `$N` (postgres) backends generate clean code. Keep this file ASCII
// only and avoid apostrophes in comments (sqlc parser is fragile here).
func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) error {
	_, err := q.db.ExecContext(ctx, createIssue,
		arg.ID,
		arg.ContentHash,
		arg.Title,
		arg.Description,
		arg.Design,
		arg.AcceptanceCriteria,
		arg.Notes,
		arg.Status,
		arg.Priority,
		arg.IssueType,
		arg.Assignee,
		arg.EstimatedMinutes,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Owner,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.ClosedAt,
		arg.ClosedBySession,
		arg.ExternalRef,
		arg.SpecID,
		arg.Metadata,
		arg.SourceRepo,
		arg.SourceSystem,
		arg.CloseReason,
		arg.Sender,
		arg.Ephemeral,
		arg.Pinned,
		arg.IsTemplate,
		arg.WispType,
		arg.MolType,
		arg.RoleType,
		arg.EventKind,
		arg.Actor,
		arg.Target,
		arg.Payload,
		arg.DueAt,
		arg.DeferUntil,
	)
	return err
}

const deleteIssue = `-- name: DeleteIssue :execrows
DELETE FROM issues WHERE id = $1
`

func (q *Queries) DeleteIssue(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIssue, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getConfigValue = `-- name: GetConfigValue :one
SELECT value FROM config WHERE key = $1
`

func (q *Queries) GetConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getIssue = `-- name: GetIssue :one
SELECT id, content_hash, title, description, design, acceptance_criteria, notes, status, priority, issue_type, assignee, estimated_minutes, created_at, created_by, owner, updated_at, started_at, closed_at, closed_by_session, external_ref, spec_id, metadata, source_repo, source_system, close_reason, sender, ephemeral, pinned, is_template, wisp_type, mol_type, role_type, event_kind, actor, target, payload, due_at, defer_until FROM issues WHERE id = $1
`

func (q *Queries) GetIssue(ctx context.Context, id string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssue, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.Title,
		&i.Description,
		&i.Design,
		&i.AcceptanceCriteria,
		&i.Notes,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Assignee,
		&i.EstimatedMinutes,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.Owner,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.ClosedAt,
		&i.ClosedBySession,
		&i.ExternalRef,
		&i.SpecID,
		&i.Metadata,
		&i.SourceRepo,
		&i.SourceSystem,
		&i.CloseReason,
		&i.Sender,
		&i.Ephemeral,
		&i.Pinned,
		&i.IsTemplate,
		&i.WispType,
		&i.MolType,
		&i.RoleType,
		&i.EventKind,
		&i.Actor,
		&i.Target,
		&i.Payload,
		&i.DueAt,
		&i.DeferUntil,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, issue_id, author, text, created_at FROM comments WHERE issue_id = $1 ORDER BY created_at
`

func (q *Queries) ListComments(ctx context.Context, issueID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Author,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfig = `-- name: ListConfig :many
SELECT key, value FROM config ORDER BY key
`

func (q *Queries) ListConfig(ctx context.Context) ([]Config, error) {
	rows, err := q.db.QueryContext(ctx, listConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDependenciesTouching = `-- name: ListDependenciesTouching :many
SELECT issue_id, depends_on_id, type, created_at, created_by, metadata, thread_id FROM dependencies
WHERE issue_id = $1 OR depends_on_id = $1
ORDER BY created_at
`

func (q *Queries) ListDependenciesTouching(ctx context.Context, id string) ([]Dependency, error) {
	rows, err := q.db.QueryContext(ctx, listDependenciesTouching, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dependency
	for rows.Next() {
		var i Dependency
		if err := rows.Scan(
			&i.IssueID,
			&i.DependsOnID,
			&i.Type,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Metadata,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT label FROM labels WHERE issue_id = $1 ORDER BY label
`

func (q *Queries) ListLabels(ctx context.Context, issueID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextChildIndex = `-- name: NextChildIndex :one
INSERT INTO child_counters (parent_id, last_child)
VALUES ($1, 1)
ON CONFLICT(parent_id) DO UPDATE SET last_child = child_counters.last_child + 1
RETURNING last_child
`

func (q *Queries) NextChildIndex(ctx context.Context, parentID string) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextChildIndex, parentID)
	var last_child int32
	err := row.Scan(&last_child)
	return last_child, err
}

const nextCounterID = `-- name: NextCounterID :one
INSERT INTO issue_counter (prefix, last_id)
VALUES ($1, 1)
ON CONFLICT(prefix) DO UPDATE SET last_id = issue_counter.last_id + 1
RETURNING last_id
`

func (q *Queries) NextCounterID(ctx context.Context, prefix string) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextCounterID, prefix)
	var last_id int32
	err := row.Scan(&last_id)
	return last_id, err
}

const readyAt = `-- name: ReadyAt :many
SELECT i.id, i.content_hash, i.title, i.description, i.design, i.acceptance_criteria, i.notes, i.status, i.priority, i.issue_type, i.assignee, i.estimated_minutes, i.created_at, i.created_by, i.owner, i.updated_at, i.started_at, i.closed_at, i.closed_by_session, i.external_ref, i.spec_id, i.metadata, i.source_repo, i.source_system, i.close_reason, i.sender, i.ephemeral, i.pinned, i.is_template, i.wisp_type, i.mol_type, i.role_type, i.event_kind, i.actor, i.target, i.payload, i.due_at, i.defer_until FROM issues i
WHERE i.status = 'open'
  AND i.ephemeral = 0
  AND i.is_template = 0
  AND (i.defer_until IS NULL OR i.defer_until <= $1)
  AND NOT EXISTS (
      SELECT 1 FROM dependencies d
      JOIN issues blocker ON blocker.id = d.depends_on_id
      WHERE d.issue_id = i.id
        AND d.type = 'blocks'
        AND blocker.status NOT IN ('closed', 'pinned')
  )
ORDER BY i.priority ASC, i.created_at ASC
`

func (q *Queries) ReadyAt(ctx context.Context, now sql.NullTime) ([]Issue, error) {
	rows, err := q.db.QueryContext(ctx, readyAt, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Issue
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ContentHash,
			&i.Title,
			&i.Description,
			&i.Design,
			&i.AcceptanceCriteria,
			&i.Notes,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.EstimatedMinutes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Owner,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.ClosedAt,
			&i.ClosedBySession,
			&i.ExternalRef,
			&i.SpecID,
			&i.Metadata,
			&i.SourceRepo,
			&i.SourceSystem,
			&i.CloseReason,
			&i.Sender,
			&i.Ephemeral,
			&i.Pinned,
			&i.IsTemplate,
			&i.WispType,
			&i.MolType,
			&i.RoleType,
			&i.EventKind,
			&i.Actor,
			&i.Target,
			&i.Payload,
			&i.DueAt,
			&i.DeferUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDependency = `-- name: RemoveDependency :execrows
DELETE FROM dependencies
WHERE issue_id = $1 AND depends_on_id = $2
`

type RemoveDependencyParams struct {
	IssueID     string `json:"issue_id"`
	DependsOnID string `json:"depends_on_id"`
}

func (q *Queries) RemoveDependency(ctx context.Context, arg RemoveDependencyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeDependency, arg.IssueID, arg.DependsOnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeLabel = `-- name: RemoveLabel :execrows
DELETE FROM labels WHERE issue_id = $1 AND label = $2
`

type RemoveLabelParams struct {
	IssueID string `json:"issue_id"`
	Label   string `json:"label"`
}

func (q *Queries) RemoveLabel(ctx context.Context, arg RemoveLabelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeLabel, arg.IssueID, arg.Label)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setConfigValue = `-- name: SetConfigValue :exec
INSERT INTO config (key, value) VALUES ($1, $2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetConfigValueParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// Use `excluded.value` (the standard ON CONFLICT pseudo-row) to avoid binding
// the value parameter twice. sqlc named-arg expansion mangles repeated args
// in INSERT...ON CONFLICT...DO UPDATE statements.
func (q *Queries) SetConfigValue(ctx context.Context, arg SetConfigValueParams) error {
	_, err := q.db.ExecContext(ctx, setConfigValue, arg.Key, arg.Value)
	return err
}
