/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PPrefixRouteImport } from './routes/p.$prefix'
import { Route as PPrefixIndexRouteImport } from './routes/p.$prefix.index'
import { Route as PPrefixListRouteImport } from './routes/p.$prefix.list'
import { Route as PPrefixIssueIdRouteImport } from './routes/p.$prefix.issue.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPrefixRoute = PPrefixRouteImport.update({
  id: '/p/$prefix',
  path: '/p/$prefix',
  getParentRoute: () => rootRouteImport,
} as any)
const PPrefixIndexRoute = PPrefixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PPrefixRoute,
} as any)
const PPrefixListRoute = PPrefixListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => PPrefixRoute,
} as any)
const PPrefixIssueIdRoute = PPrefixIssueIdRouteImport.update({
  id: '/issue/$id',
  path: '/issue/$id',
  getParentRoute: () => PPrefixRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/p/$prefix': typeof PPrefixRouteWithChildren
  '/p/$prefix/list': typeof PPrefixListRoute
  '/p/$prefix/': typeof PPrefixIndexRoute
  '/p/$prefix/issue/$id': typeof PPrefixIssueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/p/$prefix/list': typeof PPrefixListRoute
  '/p/$prefix': typeof PPrefixIndexRoute
  '/p/$prefix/issue/$id': typeof PPrefixIssueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/p/$prefix': typeof PPrefixRouteWithChildren
  '/p/$prefix/list': typeof PPrefixListRoute
  '/p/$prefix/': typeof PPrefixIndexRoute
  '/p/$prefix/issue/$id': typeof PPrefixIssueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/p/$prefix'
    | '/p/$prefix/list'
    | '/p/$prefix/'
    | '/p/$prefix/issue/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/p/$prefix/list'
    | '/p/$prefix'
    | '/p/$prefix/issue/$id'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/p/$prefix'
    | '/p/$prefix/list'
    | '/p/$prefix/'
    | '/p/$prefix/issue/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  PPrefixRoute: typeof PPrefixRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$prefix': {
      id: '/p/$prefix'
      path: '/p/$prefix'
      fullPath: '/p/$prefix'
      preLoaderRoute: typeof PPrefixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$prefix/': {
      id: '/p/$prefix/'
      path: '/'
      fullPath: '/p/$prefix/'
      preLoaderRoute: typeof PPrefixIndexRouteImport
      parentRoute: typeof PPrefixRoute
    }
    '/p/$prefix/list': {
      id: '/p/$prefix/list'
      path: '/list'
      fullPath: '/p/$prefix/list'
      preLoaderRoute: typeof PPrefixListRouteImport
      parentRoute: typeof PPrefixRoute
    }
    '/p/$prefix/issue/$id': {
      id: '/p/$prefix/issue/$id'
      path: '/issue/$id'
      fullPath: '/p/$prefix/issue/$id'
      preLoaderRoute: typeof PPrefixIssueIdRouteImport
      parentRoute: typeof PPrefixRoute
    }
  }
}

interface PPrefixRouteChildren {
  PPrefixListRoute: typeof PPrefixListRoute
  PPrefixIndexRoute: typeof PPrefixIndexRoute
  PPrefixIssueIdRoute: typeof PPrefixIssueIdRoute
}

const PPrefixRouteChildren: PPrefixRouteChildren = {
  PPrefixListRoute: PPrefixListRoute,
  PPrefixIndexRoute: PPrefixIndexRoute,
  PPrefixIssueIdRoute: PPrefixIssueIdRoute,
}

const PPrefixRouteWithChildren =
  PPrefixRoute._addFileChildren(PPrefixRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  PPrefixRoute: PPrefixRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
