package main

import (
	"errors"
	"fmt"
	"io"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/spf13/cobra"

	"github.com/rsktash/beads"
	"github.com/rsktash/beads/store"
)

// `bd doctrine` reads the project's standing laws. A doctrine is not a new
// record type: it is an active project-scoped ruling carrying an area, a law
// and a rationale, filed with `bd ruling add --doctrine`. docs/doctrine.md is
// generated from that query and never hand-edited.

// Caps on the two authored fields. A law is one sentence a reader can hold in
// mind; everything that explains it belongs in the rationale.
const (
	doctrineLawCap       = 200
	doctrineRationaleCap = 600
)

// doctrineBanner is the first line of the rendered file. It is the only thing
// standing between a generated page and someone editing it by hand.
const doctrineBanner = "<!-- generated by `bd doctrine render` — do not hand-edit -->"

func newDoctrineCmd() *cobra.Command {
	root := &cobra.Command{
		Use:   "doctrine",
		Short: "The project's standing laws (project-scoped rulings carrying an area)",
		Long: `Read the doctrine: the active project-scoped rulings that carry an area, a
law and a rationale. A law is identified by its ruling id — there is no code
column and no doctrine table.

File one with ` + "`bd ruling add \"<text>\" --doctrine --concern <area> --law \"<sentence>\"`" + `,
amend one with ` + "`--supersedes`" + `, and retire one with ` + "`bd ruling retire`" + `.
There is no edit path.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return cmd.Help()
		},
	}
	root.AddCommand(newDoctrineListCmd())
	root.AddCommand(newDoctrineRenderCmd())
	root.AddCommand(newDoctrinePromoteCmd())
	return root
}

func newDoctrineListCmd() *cobra.Command {
	var concern, workspace string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List the laws: ruling id, area, law",
		Long: `Print one line per law — its ruling id, its area and the law itself.

--concern and --workspace narrow the listing; together they mean AND. Both are
checked against the area vocabulary, so a typo is refused with the vocabulary
rather than silently listing nothing.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cc, err := openStore(cmd)
			if err != nil {
				return err
			}
			defer cc.store.Close()

			if err := validateAreaName(cc, store.AreaConcern, concern); err != nil {
				return err
			}
			if err := validateAreaName(cc, store.AreaWorkspace, workspace); err != nil {
				return err
			}

			laws, err := cc.store.ListDoctrine(cc.ctx, store.DoctrineFilter{
				Concern:   strings.TrimSpace(concern),
				Workspace: strings.TrimSpace(workspace),
			})
			if err != nil {
				return err
			}
			writeDoctrineTable(cmd.OutOrStdout(), laws)
			return nil
		},
	}
	cmd.Flags().StringVar(&concern, "concern", "", "only laws carrying this concern")
	cmd.Flags().StringVar(&workspace, "workspace", "", "only laws carrying this workspace")
	return cmd
}

func newDoctrineRenderCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "render",
		Short: "Write the whole doctrine page to stdout",
		Long: `Render every law as one markdown page, grouped by area: the concerns in
vocabulary order, then the workspaces. Within a heading each law is bold, its
rationale is the paragraph under it, and an attribution line cites the ruling.

The page is generated, so it is redirected over the file it replaces:

    bd doctrine render > docs/doctrine.md`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			cc, err := openStore(cmd)
			if err != nil {
				return err
			}
			defer cc.store.Close()

			laws, err := cc.store.ListDoctrine(cc.ctx, store.DoctrineFilter{})
			if err != nil {
				return err
			}
			areas, err := cc.store.ListAreas(cc.ctx)
			if err != nil {
				return err
			}
			writeDoctrinePage(cmd.OutOrStdout(), areas, laws)
			return nil
		},
	}
	return cmd
}

func newDoctrinePromoteCmd() *cobra.Command {
	var concern string
	cmd := &cobra.Command{
		Use:   "promote <ruling-id> --concern <name>",
		Short: "Re-scope an issue-scoped ruling to project doctrine (actor-gated: BD_ACTOR=executor is refused)",
		Long: `Move an existing ruling from its bead to the project and stamp its concern.
The row is updated in place — same id, same text, same date — so every citation
of the ruling keeps resolving. It never mints a second ruling.

Actor gating: BD_ACTOR=executor cannot promote a ruling to doctrine; a
coordinator or the owner (unset BD_ACTOR) may.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			identity, isExecutor := resolveActor()
			if isExecutor {
				return executorRefusal(identity)
			}

			id := strings.TrimSpace(args[0])
			if id == "" {
				return fmt.Errorf("ruling id is required")
			}
			concern = strings.TrimSpace(concern)
			if concern == "" {
				return fmt.Errorf("--concern is required: a project ruling has no bead to read its area from")
			}

			cc, err := openStore(cmd)
			if err != nil {
				return err
			}
			defer cc.store.Close()

			if err := validateAreaName(cc, store.AreaConcern, concern); err != nil {
				return err
			}
			if err := cc.store.PromoteDoctrine(cc.ctx, id, concern); err != nil {
				if errors.Is(err, store.ErrNotFound) {
					return fmt.Errorf("ruling %s not found", id)
				}
				return err
			}
			fmt.Fprintf(cmd.OutOrStdout(), "promoted %s to doctrine (concern %s)\n", id, concern)
			return nil
		},
	}
	cmd.Flags().StringVar(&concern, "concern", "", "the concern this law belongs to")
	return cmd
}

// validateAreaName refuses a value the vocabulary does not carry and names
// every value it does, so a writer who guessed wrong picks from a list instead
// of guessing again. An empty value is not validated: it means "unset".
func validateAreaName(cc *cmdCtx, kind, name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil
	}
	areas, err := cc.store.ListAreas(cc.ctx)
	if err != nil {
		return err
	}
	var known []string
	for _, a := range areas {
		if a.Kind != kind {
			continue
		}
		if a.Name == name {
			return nil
		}
		known = append(known, a.Name)
	}
	return fmt.Errorf("unknown %s %q — the vocabulary is: %s (add one with `bd areas add %s <name>`)",
		kind, name, strings.Join(known, ", "), kind)
}

// validateDoctrineLaw enforces the shape of a law: present, one sentence, and
// punctuated as one. The cap is on runes, not bytes, so a law in Cyrillic gets
// the same room as one in ASCII.
func validateDoctrineLaw(law string) error {
	law = strings.TrimSpace(law)
	if law == "" {
		return fmt.Errorf("--doctrine requires --law: one imperative sentence, at most %d characters, ending in a full stop", doctrineLawCap)
	}
	if n := utf8.RuneCountInString(law); n > doctrineLawCap {
		return fmt.Errorf("--law is %d characters; the cap is %d — a law is one sentence, the reasoning belongs in --rationale", n, doctrineLawCap)
	}
	if !strings.HasSuffix(law, ".") {
		return fmt.Errorf("--law must end in a full stop; it is one complete sentence, not a heading")
	}
	return nil
}

// validateDoctrineRationale caps the rationale. It is optional: a law that
// needs no explanation carries none.
func validateDoctrineRationale(rationale string) error {
	if n := utf8.RuneCountInString(strings.TrimSpace(rationale)); n > doctrineRationaleCap {
		return fmt.Errorf("--rationale is %d characters; the cap is %d — a longer argument belongs on the ruling's bead", n, doctrineRationaleCap)
	}
	return nil
}

// concernList splits the comma-separated concern column, dropping empties. A
// ruling that inherited its areas from a bead carries several.
func concernList(s string) []string {
	var out []string
	for _, c := range strings.Split(s, ",") {
		if c = strings.TrimSpace(c); c != "" {
			out = append(out, c)
		}
	}
	return out
}

// rulingsInConcern keeps the rulings naming one concern, membership-wise.
func rulingsInConcern(list []beads.Statement, concern string) []beads.Statement {
	var out []beads.Statement
	for _, r := range list {
		for _, c := range concernList(r.Concern) {
			if c == concern {
				out = append(out, r)
				break
			}
		}
	}
	return out
}

// doctrineArea is the area column of the listing: the law's concern, its
// workspace when it carries no concern.
func doctrineArea(st beads.Statement) string {
	if st.Concern != "" {
		return st.Concern
	}
	if st.Workspace != "" {
		return st.Workspace
	}
	return "project"
}

// writeDoctrineTable prints one line per law — ruling id, area, law — with the
// first two columns padded so the laws line up under each other.
func writeDoctrineTable(w io.Writer, laws []beads.Statement) {
	if len(laws) == 0 {
		fmt.Fprintln(w, "(no doctrine)")
		return
	}
	idW, areaW := 0, 0
	for _, st := range laws {
		idW = max(idW, utf8.RuneCountInString(st.ID))
		areaW = max(areaW, utf8.RuneCountInString(doctrineArea(st)))
	}
	for _, st := range laws {
		fmt.Fprintf(w, "%s  %s  %s\n",
			padTopicCell(st.ID, idW),
			padTopicCell(doctrineArea(st), areaW),
			headlineText(rulingLineText(st)))
	}
}

// doctrineGroup is one heading of the rendered page and the laws under it.
type doctrineGroup struct {
	name string
	laws []beads.Statement
}

// doctrineGroups buckets the laws under their headings: one per concern in
// vocabulary order (which is the seed order — authority, sync, tokens, schema,
// catalog, frontend, all — with later additions after it), then one per
// workspace, then any area the vocabulary no longer names, alphabetically, so
// a renamed area can never drop a law off the page. A law carrying a concern
// is filed under it, and under every concern it names; only a law with no
// concern at all falls through to its workspace.
func doctrineGroups(areas store.Areas, laws []beads.Statement) []doctrineGroup {
	byConcern := map[string][]beads.Statement{}
	byWorkspace := map[string][]beads.Statement{}
	for _, st := range laws {
		if cs := concernList(st.Concern); len(cs) > 0 {
			for _, c := range cs {
				byConcern[c] = append(byConcern[c], st)
			}
			continue
		}
		if st.Workspace != "" {
			byWorkspace[st.Workspace] = append(byWorkspace[st.Workspace], st)
		}
	}

	var out []doctrineGroup
	drain := func(kind string, m map[string][]beads.Statement) {
		for _, a := range areas {
			if a.Kind != kind {
				continue
			}
			if group, ok := m[a.Name]; ok {
				out = append(out, doctrineGroup{name: a.Name, laws: group})
				delete(m, a.Name)
			}
		}
		leftover := make([]string, 0, len(m))
		for name := range m {
			leftover = append(leftover, name)
		}
		sort.Strings(leftover)
		for _, name := range leftover {
			out = append(out, doctrineGroup{name: name, laws: m[name]})
		}
	}
	drain(store.AreaConcern, byConcern)
	drain(store.AreaWorkspace, byWorkspace)
	return out
}

// writeDoctrinePage renders the whole file: the do-not-edit banner, a title,
// then a heading per area with each law in bold, its rationale under it and an
// attribution line citing the ruling that carries it.
func writeDoctrinePage(w io.Writer, areas store.Areas, laws []beads.Statement) {
	fmt.Fprintln(w, doctrineBanner)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "# Doctrine")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Standing, cross-bead decisions. Every later-filed, unclosed bead must respect")
	fmt.Fprintln(w, "them. Each law is a project-scoped ruling; to change one, file a ruling that")
	fmt.Fprintln(w, "supersedes the cited id and render this page again.")

	groups := doctrineGroups(areas, laws)
	if len(groups) == 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "(no doctrine)")
		return
	}
	for _, g := range groups {
		fmt.Fprintln(w)
		fmt.Fprintf(w, "## %s\n", g.name)
		for _, st := range g.laws {
			fmt.Fprintln(w)
			fmt.Fprintf(w, "**%s**\n", singleLine(rulingLineText(st)))
			if r := strings.TrimSpace(st.Rationale); r != "" {
				fmt.Fprintln(w)
				fmt.Fprintln(w, r)
			}
			fmt.Fprintln(w)
			fmt.Fprintln(w, doctrineAttribution(st))
		}
	}
}

// doctrineAttribution is the trailing line under a law: the ruling that
// carries it and the topic it belongs to.
func doctrineAttribution(st beads.Statement) string {
	if topic := strings.TrimSpace(st.Topic); topic != "" {
		return fmt.Sprintf("— %s (%s)", st.ID, topic)
	}
	return "— " + st.ID
}

// singleLine collapses whitespace without truncating: a law is already capped,
// and the bold line must not carry a newline that would break the markdown.
func singleLine(s string) string {
	return strings.Join(strings.Fields(strings.NewReplacer("\r", " ", "\n", " ", "\t", " ").Replace(s)), " ")
}
