// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddComment(ctx context.Context, arg AddCommentParams) error
	AddDependency(ctx context.Context, arg AddDependencyParams) error
	AddLabel(ctx context.Context, arg AddLabelParams) error
	AddMemory(ctx context.Context, arg AddMemoryParams) error
	BlocksReachableFrom(ctx context.Context, arg BlocksReachableFromParams) ([]string, error)
	// Used by the adaptive id-length selector: more issues -> longer hash.
	CountIssuesWithPrefix(ctx context.Context, likePattern string) (int64, error)
	// Dialect-portable queries: named args via sqlc.arg() so both `?` (sqlite)
	// and `$N` (postgres) backends generate clean code. Keep this file ASCII
	// only and avoid apostrophes in comments (sqlc parser is fragile here).
	CreateIssue(ctx context.Context, arg CreateIssueParams) error
	DeleteIssue(ctx context.Context, id string) (int64, error)
	DeleteMemory(ctx context.Context, id int64) (int64, error)
	GetConfigValue(ctx context.Context, key string) (string, error)
	GetIssue(ctx context.Context, id string) (Issue, error)
	ListComments(ctx context.Context, issueID string) ([]Comment, error)
	ListConfig(ctx context.Context) ([]Config, error)
	ListDependenciesTouching(ctx context.Context, id string) ([]Dependency, error)
	ListLabels(ctx context.Context, issueID string) ([]string, error)
	ListMemoriesByKey(ctx context.Context, key interface{}) ([]Memory, error)
	NextChildIndex(ctx context.Context, parentID string) (int64, error)
	NextCounterID(ctx context.Context, prefix string) (int64, error)
	ReadyAt(ctx context.Context, now sql.NullTime) ([]Issue, error)
	RemoveDependency(ctx context.Context, arg RemoveDependencyParams) (int64, error)
	RemoveLabel(ctx context.Context, arg RemoveLabelParams) (int64, error)
	// Use `excluded.value` (the standard ON CONFLICT pseudo-row) to avoid binding
	// the value parameter twice. sqlc named-arg expansion mangles repeated args
	// in INSERT...ON CONFLICT...DO UPDATE statements.
	SetConfigValue(ctx context.Context, arg SetConfigValueParams) error
}

var _ Querier = (*Queries)(nil)
