// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddComment(ctx context.Context, arg AddCommentParams) error
	AddDependency(ctx context.Context, arg AddDependencyParams) error
	AddEvent(ctx context.Context, arg AddEventParams) error
	AddLabel(ctx context.Context, arg AddLabelParams) error
	// Forward step in the cycle-detection BFS: who does `issue_id` block?
	BlocksReachableFrom(ctx context.Context, arg BlocksReachableFromParams) ([]string, error)
	// count of issues that have a parent-child dep pointing AT them from this parent
	ChildCount(ctx context.Context, parentID string) (int64, error)
	// Dialect-portable: positional placeholders are introduced via sqlc.arg() so
	// both `?` (sqlite) and `$N` (postgres) backends generate clean code.
	CreateIssue(ctx context.Context, arg CreateIssueParams) error
	DeleteIssue(ctx context.Context, id string) (int64, error)
	GetIssue(ctx context.Context, id string) (Issue, error)
	ListComments(ctx context.Context, issueID string) ([]Comment, error)
	ListDependenciesTouching(ctx context.Context, id string) ([]Dependency, error)
	ListEvents(ctx context.Context, issueID string) ([]Event, error)
	ListLabels(ctx context.Context, issueID string) ([]string, error)
	// Open, non-ephemeral, non-template, no `blocks` dep from a non-{closed,pinned}
	// issue, not deferred. `now` is supplied by the caller for portability.
	ReadyAt(ctx context.Context, now sql.NullTime) ([]Issue, error)
	RemoveDependency(ctx context.Context, arg RemoveDependencyParams) (int64, error)
	RemoveLabel(ctx context.Context, arg RemoveLabelParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
